---
title: "Reading_data_from_the_web"
output: github_document
date: 10/14/2020
---

```{r setup}
library(tidyverse)
```

## `pivot_longer`

Load the PULSE data

```{r}
pulse_data =
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

Wide format to long format

```{r}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
```

rewrite, combine, and extend (to add a mutate)
```{r}
pulse_data =
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
```

## `pivot_wider`

Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

#tidy dataframe - long

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )

# tidy but wider now
```

## Binding rows using the LoR data

First step is import each table

```{r}
fellowship_ring = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "b3:d6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "f3:h6") %>% 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "j3:l6") %>% 
  mutate(movie = "return_king")
```

Bind all the rows together

```{r}
lotr_tidy=
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male, 
    names_to = "gender",
    values_to = "words"
  )
```

## Joining datasets

Import and clean the FAS datasets.

```{r}
pups_df = 
  read_csv("./data_import_examples/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))

litters_df = 
  read_csv("./data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  relocate(litter_number) %>% 
  separate(group, into = c("dose", "day_of_tx"), sep = 3) #"sep=" separate after 3 characters
```

Joining them

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  arrange(litter_number) %>% 
  relocate(litter_number, dose, day_of_tx)
```

