---
title: "Strings and Factors"
output: github_document
date: 10/15/2020
---

```{r setup, include = FALSE}
library(tidyverse)

library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Strings  and regex

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")
str_detect(string_vec, "j")
str_detect(string_vec, "e")
str_detect(string_vec, "Jeff")

str_replace(string_vec, "jeff", "Jeff")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think") #start with
str_detect(string_vec, "i think$") #end with
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush") #Bush OR bush
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") #. matches anything
str_detect(string_vec, "7\\.11") # \ tells R that you want the . to actually be a .

```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

## Factors

```{r}
vec_sex = factor(c("male", "male", "female", "female"))

vec_sex

as.numeric(vec_sex)
```

What hapens if I relevel ...

```{r}
vec_sex = fct_relevel(vec_sex, "male")

vec_sex

as.numeric(vec_sex)
```

## NSDUH